### ISSUE TITLE
Are there plans to license this code?

### ISSUE THREAD

**Issue by ccbxxy** [Captain-Sandwich/akai.py#1]
I'm building a GPL/PFL licensed universal sysex editor and am raiding compatibly licensed code.

Thanks
ccbxxy

**Comment by Captain-Sandwich** [comment]
I haven't touched it in ages, but if you can get some use out of this code, go ahead. I only ever used it to upload simple waveforms to the Akai to use it with a midi keyboard as a bad subtractive synth.

akai.py is GPL now. Just out of curiosity, is your sysex editor somewhere on github?

**Comment by ccbxxy** [comment]
Under development but yes: https://github.com/ccbxxy/sysex
Documentation is being developed here: https://sysex.miraheze.org/wiki/UR

I'm days away from being able to do command-line based manipulation of a Yamaha reface YC.

**Comment by Captain-Sandwich** [comment]
closing
